runtime: python37
instance_class: F4
automatic_scaling:
  min_instances: 0

handlers:

- url: /sw\.js
  static_files : sw.js
  upload: sw\.js
  expiration: "1s"

- url: /robots\.txt
  static_files : robots.txt
  upload: robots\.txt

- url: /static
  static_dir: static
  expiration: "1s"

- url: /img
  static_dir: img

- url: .*
  script: auto
  secure: always
