runtime: python37

handlers:

- url: /sw\.js
  static_files : sw.js
  upload: sw\.js
  expiration: "1s"

- url: /static
  static_dir: static
  expiration: "1s"

- url: /img
  static_dir: img

- url: .*
  script: auto
  secure: always
