runtime: python38
instance_class: F4
service: stageing
automatic_scaling:
  min_instances: 0

handlers:

- url: /_ah/api/.*
  script: auto
  secure: always

- url: /sw\.js
  static_files : dist/sw.js
  upload: dist/sw\.js
  expiration: "1s"

- url: /robots\.txt
  static_files : robots.txt
  upload: robots\.txt
  
- url: /(.*\..*)$
  static_files: dist/\1
  upload: dist/.*\..*$
  
- url: /assets
  static_dir: dist/assets
  expiration: "1s"

- url: /.*
  static_files: dist/index.html
  upload: dist/index.html
  secure: always
