  openapi: 3.0.0

  info:
    title: bgp
    description: Big Cannon Project API
    version: '1.0'

  components:
    securitySchemes:
      jwt:
        type: http
        scheme: bearer
        bearerFormat: JWT
        x-bearerInfoFunc: api.auth_api.AuthApi.decode_token

  security:
    - jwt: []

  servers:
    - url: /_ah/api

  paths:
    /fetch_map:
      post:
        operationId: api.MapApi.fetch_map
        
        requestBody:
          description: Request for Map Data
          required: true
          content:
            application/json:
              schema:
                type: object
                properties:
                  page:
                    type: number
                  transaction:
                    type: number

        responses:
          200:
            description: Fetch the Map data
            content:
              application/json:
                schema:
                  type: object
                  
    /fetch_sites:
      post:
        operationId: api.MapApi.fetch_sites
        
        requestBody:
          description: Request for Site Data
          required: true
          content:
            application/json:
              schema:
                type: object
                properties:
                  page:
                    type: number
                  transaction:
                    type: number

        responses:
          200:
            description: Fetch the Ste data
            content:
              application/json:
                schema:
                  type: object
                  
    /update_map:
      post:
        operationId: api.MapApi.update_map
        
        responses:
          200:
            description: Updtae the Map data
            content:
              application/json:
                schema:
                  type: object
    /fetch_user:
      post:
        operationId: api.UserApi.fetch_user

        responses:
          200:
            description: Fectch the user data
            content:
              application/json:
                schema:
                  type: object

    /get_location:
      post:
        operationId: api.LocationApi.get_location
        
        requestBody:
          description: A new location
          required: true
          content:
            application/json:
              schema:
                type: object
                required:
                  - lat
                  - lng
                properties:
                  lat:
                    type: number
                  lng:
                    type: number

        responses:
          200:
            description: Fetch the location data
            content:
              application/json:
                schema:
                  type: object
                  
    /add_photo:
      post:
        operationId: api.GunApi.add_photo
        
        requestBody:
          description: A new photo
          required: true
          content:
            application/json:
              schema:
                type: object


        responses:
          200:
            description: Add a Photo
            content:
              application/json:
                schema:
                  type: object

    /add_record:
      post:
        operationId: api.GunApi.add_record
        
        requestBody:
          description: A new record
          required: true
          content:
            application/json:
              schema:
                type: object


        responses:
          200:
            description: Add a new record
            content:
              application/json:
                schema:
                  type: object

    /set_record:
      post:
        operationId: api.GunApi.set_record
        
        requestBody:
          description: An updated record
          required: true
          content:
            application/json:
              schema:
                type: object


        responses:
          200:
            description: update a record
            content:
              application/json:
                schema:
                  type: object
