  openapi: 3.0.0

  info:
    title: bgp
    description: Big Cannon Project API
    version: '1.0'

  components:
    securitySchemes:
      jwt:
        type: http
        scheme: bearer
        bearerFormat: JWT
        x-bearerInfoFunc: api.AuthApi.decode_token

  security:
    - jwt: []

  servers:
    - url: https://localhost:8000/_ah/api/qr8

  paths:
    /fetch_map_2:
      post:
        operationId: api.MapApi.fetch_map

        responses:
          200:
            description: Fectch the Map data
            content:
              application/json:
                schema:
                  type: object
