  openapi: 3.0.0

  info:
    title: bgp
    description: Big Cannon Project API
    version: '1.0'

  components:
    securitySchemes:
      jwt:
        type: http
        scheme: bearer
        bearerFormat: JWT
        x-bearerInfoFunc: api.auth_api.AuthApi.decode_token

  security:
    - jwt: []

  servers:
    - url: http://localhost:8080/_ah/api/bcp

  paths:
    /fetch_map:
      post:
        operationId: api.MapApi.fetch_map

        responses:
          200:
            description: Fectch the Map data
            content:
              application/json:
                schema:
                  type: object
    
    /fetch_user:
      post:
        operationId: api.UserApi.fetch_user

        responses:
          200:
            description: Fectch the Map data
            content:
              application/json:
                schema:
                  type: object
